# Nombre del workflow
name: Mi primer workflow

# Evento que activa el workflow. En este caso, se activa cada vez que se hace un 'push' al repositorio.
on: 
  push:

# Definición de los trabajos (jobs) que se van a ejecutar
jobs:
  hola-mundo:  # Nombre interno del job
    runs-on: ubuntu-latest  # El job se ejecuta en un contenedor con Ubuntu (última versión disponible)

    # Definicion de variables de entorno (env) para el job
    env:
      MENSAJE: "¡Bienvenido a Github Actions!" # variable personalizado
      
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4 # Accion publica desde Github Marketplace

    - name: Mostrar mensaje  # imprime mensaje y nombre del usuario
      run: |
        echo "${{ env.MENSAJE }}"
        echo "este workflow fue ejecutado por el usuario: ${{ github.actor }}" 
      # Muestra el nombre del usuario que hizo push (contexto Github)
